global:
  scrape_interval: 5s       # coleta métricas a cada 5 segundos (demo responsiva)
  evaluation_interval: 5s

scrape_configs:

  - job_name: "ridefleet"
    static_configs:
      - targets:
          - "nginx:80"      # coleta via load balancer (distribui entre backend1/2)
    metrics_path: /metrics

  - job_name: "ridefleet-backend1"
    static_configs:
      - targets:
          - "backend1:5000"
    metrics_path: /metrics

  - job_name: "ridefleet-backend2"
    static_configs:
      - targets:
          - "backend2:5000"
    metrics_path: /metrics
