$kind: http-request
url: "{{base_url}}/metrics"
method: GET
scripts:
  - type: afterResponse
    code: |-
      pm.test('Status 200', () => pm.response.to.have.status(200));
      pm.test('Tem métrica de motoristas', () => {
          pm.expect(pm.response.text()).to.include('ridefleet_motoristas_disponiveis');
      });
    language: text/javascript
order: 3000
